added navbar
mariyasada/ecommerce pull request #1
Opened 2022-03-14 06:22 UTC by mariyasada

![nav](https://user-images.githubusercontent.com/77275100/158116273-d117a6cc-2327-4183-8522-664a57adacb1.PNG)
added navbar

2022-03-14 18:14 UTC, tusharkandpal requested changes
Looks good!

2022-03-14 18:14 UTC, tusharkandpal commented on src/index.css
>  code {
Can remove this `code` tag. If not in use

2022-03-15 03:41 UTC, mariyasada commented on src/index.css
>  code {
Sure

2022-03-15 05:30 UTC, tusharkandpal approved these changes

2022-03-15 10:35 UTC, Raghav888 approved these changes
Approved

2022-03-15 15:35 UTC, merged